name: ShulkerBoxPreview
main: tech.ice.plugins.ShulkerBoxPreview.Main
version: 1.2
author: YT_iceice
commands:
  sbpreload:
    description: 重新讀取所有配置檔案
    usage: /sbpreload
  sbppreview:
    description: 切換是否啟用功能預覽
    usage: /sbppreview <on/off>
    aliases: sbpp