name: ShulkerBoxPreview
main: tech.ice.plugins.ShulkerBoxPreview.Main
version: 1.0-SNAPSHOT
api-version: 1.19
author: YT_iceice
commands:
  sbpreload:
    description: 重新讀取所有配置檔案
    usage: /sbpreload